### ISSUE TITLE
get_absolute_url() in event Model

### ISSUE THREAD

**Issue by ksut** [BrandonDavidDee/bcal#1]
Hi Brandon,  Thanks for sharing the code. Can you please add some more detail, if possible upload model.py ? I have noticed in bcal.py you are using get_absolute_url() on event but not able to make proper get_absolute_url() return in model for event.

**Comment by Longnguyen111** [comment]
Hi Brandon, Thanks for sharing the code. Can you please add some more detail, if possible upload model.py ? Or share full code. Thank You v

**Comment by BrandonDavidDee** [comment]
I'm so sorry, I never saw these comments until now. I'd moved all my repos for work and forgot I had left this one out there. I know it's long overdue but will get on this asap.

**Comment by BrandonDavidDee** [comment]
I just pushed an update that demonstrates bcal.py in a simple but complete Django project with Client and Event models. This should address any confusion over the the get_absolute_url method on the Event model. Again, I apologize for the delay.
